### PR TITLE
Update to Bulma 0.7.2

### PR DESCRIPTION
**Pull request by danielRomero**
Upgrade bulma to 1.7.2

### CODE REVIEW

**Comment by erikdahlstrand** [comment]
Thank you @danielRomero . This PR changes file permissions from 100755 → 100644 on all files. I wouldn't say this is wrong per se but it should be done in a separate commit and not as a part of the upgrade. Will you please change that and make another PR?

You can do that by telling Git to ignore file mode:
```git config core.fileMode false```

**Comment by danielRomero** [comment]
Thanks @erikdahlstrand I have not noticed that change when I did the PR 😅 
changed!

**Comment by erikdahlstrand** [comment]
Great! Did you remember to push the changes? As far as I can see it's the same commit.

image

**Comment by danielRomero** [comment]
I did right now another PR to change this in master #39
Sorry if I misunderstood you, I don't know if I'm doing this well 😅

**Comment by erikdahlstrand** [comment]
Thank you for your contribution @danielRomero.

**Pull request merged**
