### PR TITLE
Update to Bulma 0.5.1

### PR DESCRIPTION
**Pull request by davidwessman**
- Also updates README and .gemspec

### CODE REVIEW

**Comment by BilalBudhani** [comment]
@davidwessman 

I pointed my gem to your repo to run on my local machine

```
gem 'bulma-rails', github: 'davidwessman/bulma-rails'
```
but I'm getting the following error 
actionview template error at 2017-08-02 20-39-57

Ruby: 2.4.1
Rails: 5.1.2

**Comment by iburton** [comment]
@BilalBudhani, can you narrow it down to a reproducible test case?  I have tried a few things using your ruby/rails versions and cannot reproduce any error messaging.

**Comment by davidwessman** [comment]
Hm, I also encountered this error.
Could it depend on sass vs scss? Something syntactic?

**Comment by davidwessman** [comment]
@BilalBudhani @iburton 
Bulma version 0.5.1 seems to have fixed this!

**Comment by davidwessman** [comment]
I moved over to using yarn to install Bulma as well, since it is released there directly :)

**Comment by luizpicolo** [comment]
I too @davidwessman

**Comment by lemuelbarango** [comment]
Just wondering when this version will be merged?

**Comment by kirqe** [comment]
@joshuajansen, are you going to maintain the repo?

**Comment by joshuajansen** [comment]
@kirqe sorry guys! Totally missed this PR. I'll merge and push to Rubygems right away.

**Pull request merged**
