### PR TITLE
Update to Bulma 0.6.0

### PR DESCRIPTION
**Pull request by erikdahlstrand**

### CODE REVIEW

**Comment by erikdahlstrand** [comment]
Five minutes have past and still not merged... I'm disappointed :wink: #29

**Comment by pedroadame** [comment]
Two weeks and unmerged? Incredible.

**Comment by erikdahlstrand** [comment]
Hi @pedroadame 

In the future I will help Joshua to keep this repo in sync with Bulma. I now have git commit rights to this repo, but I don't want to merge this in until I also have rights to push new gem releases. I've talked to Joshua and he's currently on holiday. As soon as he's back at his laptop I'll be given gem push rights.

In the meantime you can point to my branch in your `Gemfile`.

    gem 'bulma-rails', github: 'erikdahlstrand/bulma-rails'

**Comment by pedroadame** [comment]
Hi @erikdahlstrand 

I understand your position completely. Thank you.
Although I ended up using `npm` to manage frontend packages and adding `node_modules` to asset pipeline as Rails 5.1 comes with `yarn` support,

**Comment by joshuajansen** [comment]
@erikdahlstrand I got back from my holiday today and just gave you push access to Rubygems! Sorry for keeping you guys waiting and thanks for helping out @erikdahlstrand 👏

**Pull request merged**
