### PR TITLE
Update to Bulma 0.9.3

### PR DESCRIPTION
**Pull request by jhunschejones**
### Description
This PR upgrades the gem to use the newest version of Bulma. The diff between the two versions can be seen [here](https://github.com/jgthms/bulma/compare/0.9.2...0.9.3), and the release notes are available [here](https://github.com/jgthms/bulma/releases/tag/0.9.3). I used the official download from the [Bulma releases page](https://github.com/jgthms/bulma/releases/download/0.9.3/bulma-0.9.3.zip) for these file changes.

### CODE REVIEW

**Comment by ozkar99** [comment]
Any reason why this hasnt been merged yet?

**Comment by jhunschejones** [comment]
> Any reason why this hasnt been merged yet?

I think we're just waiting on @joshuajansen 👍🏻

**Comment by joshuajansen** [comment]
Jep! Thanks for mentioning me @jhunschejones, will merge and push the update to Rubygems.

**Comment by joshuajansen** [comment]
Done! Thanks for the PR @jhunschejones.

**Pull request merged**
