### PR TITLE
Upgrading to bulma v0.0.15 and including the image folder.

### PR DESCRIPTION
**Pull request by farmisen**
Updated to v0.0.15 and added the image folder that was horking the asset pipeline in 0.0.14.

### CODE REVIEW

**Comment by joshuajansen** [comment]
Thanks! Could you elaborate on the horking image folder?

**Comment by hjoseph96** [comment]
Without it, you get:

`Sass::SyntaxError at / File to import not found or unreadable: images.`

**Comment by hjoseph96** [comment]
using this gem, so please merge this ASAP

**Comment by delynn** [comment]
@Copywright I'm seeing the `File to import not found or unreadable: images` error as well, but the issue is not that the project is missing an images directory. The issue is that https://github.com/joshuajansen/bulma-rails/blob/master/app/assets/stylesheets/bulma/elements/elements.sass#L6 attempts to import an images file that is missing from the gem package. 

:+1: for getting the gem updated to 0.0.15 however.

**Comment by joshuajansen** [comment]
@delynn thats quite odd since the `images.sass` file is present in that folder (https://github.com/joshuajansen/bulma-rails/blob/master/app/assets/stylesheets/bulma/elements/images.sass) and should be importable. I'm trying to reproduce the error but for me it just works fine.. :( Which version of Rails are you using?

**Comment by delynn** [comment]
I just started a new project with Rails 5.0. I initially thought that might be
it, but I discovered the missing images file after doing a `bundle open`. Are
you specifying a local path, or the GitHub repo in the Gemfile by chance?

On Tue, Feb 23, 2016 at 12:42 AM, Joshua Jansen notifications@github.com
wrote:
@delynn [https://github.com/delynn] thats quite odd since the images.sass file is present in that folder ( 
https://github.com/joshuajansen/bulma-rails/blob/master/app/assets/stylesheets/bulma/elements/images.sass
[https://github.com/joshuajansen/bulma-rails/blob/master/app/assets/stylesheets/bulma/elements/images.sass] ) and should be importable. I'm trying to reproduce the error but for me it
just works fine.. :( Which version of Rails are you using?

—
Reply to this email directly or view it on GitHub
[https://github.com/joshuajansen/bulma-rails/pull/1#issuecomment-187586149] .[https://github.com/notifications/beacon/AAAA3dTSE7Cp_jU0BbSID0lPrHgTDzV2ks5pnAT1gaJpZM4HfMoN.gif]

**Comment by joshuajansen** [comment]
I found the reason for the error. It had to do with my git index being corrupt locally, because of this, the `images.sass` wasn't included when building the gem. After starting with a fresh clone, I was able to make a proper build.

@farmisen the image folder wasn't needed, and I just updated the gem to `0.0.15`, so we won't be needing this PR anymore, thanks though! :+1: 

I verified that the current version works, so I'm gonna yank `0.0.14` and you guys can update your gems :smile:

**Comment by delynn** [comment]
I was wondering if it was something weird like that. Thanks for fixing this! :+1:

**Pull request closed without merging**
